### ISSUE TITLE
Keyboard Teleop doesn't work

### ISSUE THREAD

**Issue by diogolopes18-cyber** [f1tenth-dev/simulator#10]
When I try to run the script **keyboard_teleop.py** in order to enable the W-A-S-D keys to control the functioning of the vehicle, it doesn't receive any keyboard input.
I was running simultaneously the **roslaunch f1tenth-sim multi-TEB.launch** and the only thing I can control is the **2D Nav Goal** in Rviz. Do you have any idea how to fix it?
The data from LIDAR is received as if the cars are stopped, even if I press the keyboard control movement W-A-S-D.

**Comment by varundevsukhil** [comment]
To manually control the racecar, you must set the `keyboard_control` flag included in `simulator.launch`. The TEB launch command will bring up the navigation stack and assign priority to autonomous control, so the manual teleop commands will be rejected. Follow the instructions in this [section in the wiki](https://github.com/f1tenth-dev/simulator/wiki/Quick-Start#keyboard-tele-operation).

**Comment by diogolopes18-cyber** [comment]
But even when I launch the **roslaunch f1tenth-sim multi-TEB-launch** there is no visible moving of the cars in the Gazebo environment.

**Comment by diogolopes18-cyber** [comment]
I've tried once again to run the following roslaunch:

**roslaunch f1tenth-sim simulator.launch run_gazebo:=true keyboard_control:=true**

But the car doesn't move at all, and I don't get any change in the values published on **/car_1/base/odom** topic when I click W-A-S-D

**Comment by varundevsukhil** [comment]
Is the terminal from where the launch command was issued the active window? The racecar will not receive commands from the keyboard if the terminal does not record keystrokes.

**Comment by diogolopes18-cyber** [comment]
Yes, I was trying to input the keys from the same terminal from where I've launched the roslaunch command
![terminal](https://user-images.githubusercontent.com/57946086/79007204-983eab00-7b52-11ea-8904-a2495769d607.png)

**Comment by diogolopes18-cyber** [comment]
I've tried to enter the keys here.

**Comment by diogolopes18-cyber** [comment]
@varundevsukhil I've tried to run the `roslaunch` in one terminal and the `keyboard_teleop.py` in another terminal and still the car in the Gazebo environment doesn't move at all, and I don't get any change in linear position on the X axis.

**Comment by varundevsukhil** [comment]
I haven't faced this issue and I am not able to replicate it. Can you try whatever you are doing and post the output of `rqt_graph` here?

**Comment by diogolopes18-cyber** [comment]
Sure, I'll post the rqt_graph right here.

**Comment by diogolopes18-cyber** [comment]
![github_issue](https://user-images.githubusercontent.com/57946086/79056783-af17f700-7c51-11ea-977b-2c87f5ed00dd.png)

**Comment by varundevsukhil** [comment]
I see that the `controller_manager` nodes are missing. Did you install the dependancies as described in the wiki?

**Comment by diogolopes18-cyber** [comment]
I thought I had installed it. But is it on the tutorial page?

**Comment by varundevsukhil** [comment]
Try this: `sudo apt-get install -y ros-melodic-navigation ros-melodic-teb-local-planner* ros-melodic-ros-control ros-melodic-ros-controllers ros-melodic-gazebo-ros-control ros-melodic-ackermann-msgs ros-melodic-serial qt4-default`

**Comment by diogolopes18-cyber** [comment]
Those packages were already installed, and I've tried again to run the  `rosrun f1tenth-sim keyboard_teleop.py` in order to control the car, and it doesn't move.

**Comment by varundevsukhil** [comment]
I do not understand why you are running the `keyboard_teleop.py`, that node is launched by setting the `keyboard_control:=true` in the launch command. The controller manager is missing from the `rqt_graph`, so that package is either not installed or not launching properly. 

The only other issues I can think of are the environment not sourced, but just to be sure can you post the output of the terminal from where the launch command is issued and another terminal output for `rostopic list`. 

I would like to see everything in the terminal from when you issue the launch command, and also a screenshot of the Gazebo GUI.

If nothing else works, I can provide you with a link to a docker image that you can run online.

**Comment by diogolopes18-cyber** [comment]
![GUI](https://user-images.githubusercontent.com/57946086/79111314-32ca0480-7d74-11ea-8bc2-2f75c2e75860.png)
![rostopic](https://user-images.githubusercontent.com/57946086/79111318-33fb3180-7d74-11ea-83fc-23904b8e8e0a.png)
![roslaunch_output](https://user-images.githubusercontent.com/57946086/79111320-3493c800-7d74-11ea-9a53-53d0641ace2f.png)

**Comment by varundevsukhil** [comment]
For pic. 1, read this section on [first time setup](https://github.com/f1tenth-dev/simulator/wiki/Quick-Start#first-time-setup) to install the virtual race track.

The terminal says the `controller_manager` ROS interface is missing; this is usually fixed by installing the specific Gazebo ROS contol meta-package:

```
$ sudo apt-get install -y ros-melodic-controller-manager ros-melodic-joint-state-controller ros-melodic-effort-controllers ros-melodic-position-controllers
```

**Comment by f1tenth-dev** [comment]
Stale issue. Closed!

**Comment by diogolopes18-cyber** [comment]
@varundevsukhil I still haven't been able to use the `keyboard teleop`, it still gives me the same error, and I have already install the `controller_manager` package:

"[WARN] [1586891692.510636, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface."
