### ISSUE TITLE
Navigation Goal Reached never stop

### ISSUE THREAD

**Issue by FreshmanD** [f1tenth-dev/simulator#11]
Hi, when I using the navigation.launch, I set a goal in rviz, and the car reached the goal point. however, it doesn't stop, and continue move very fast, finally crash the wall. And if I set a new goal, the palnner will not generate a new path to follow.

**Comment by varundevsukhil** [comment]
This issue is related to the ROS navigation stack and not with the F1/10 simulator. Please open an issue on their GitHub.
