### ISSUE TITLE
No `simulator.launch` launch file!

### ISSUE THREAD

**Issue by Micrified** [f1tenth-dev/simulator#14]
Having followed the installation guide, I encountered two issues in the [First Time Setup](https://github.com/f1tenth-dev/simulator/wiki/Quick-Start) sections of the Wiki: 

1. Manually transferring course files to the gazebo workspace does not seem to work. That is because the instruction asks we run `cp -r autosim_ws/src/simulator/world/race_track .gazebo/models/`, and the hidden directory `.gazebo` does not in fact exist. I created it nonetheless and copied the files there.

2. Launching with `roslaunch` fails because the launch file doesn't actually exist (`roslaunch f1tenth-sim simulator.launch run_gazebo:=true`). I used `find` to try and locate the launch file (should it be misplaced) but no results were found for `simulator.launch`.

**Comment by varundevsukhil** [comment]
The wiki has been updated. Replace `simulator.launch` with `simulator.access` in the launch command. The argument `run_gazebo` is no longer necessary with the current release.

**Comment by Micrified** [comment]
@varundevsukhil Thanks for your answer! I really appreciate the outstanding response time! Unfortunately this does not work either. Here is the directory layout of `src` you get after performing the cloning and installation steps: 
```
./
├── CMakeLists.txt -> /opt/ros/melodic/share/catkin/cmake/toplevel.cmake
├── hector_slam
│   ├── README.txt
│   ├── hector_compressed_map_transport
│   ├── hector_geotiff
│   ├── hector_geotiff_plugins
│   ├── hector_imu_attitude_to_tf
│   ├── hector_imu_tools
│   ├── hector_map_server
│   ├── hector_map_tools
│   ├── hector_mapping
│   ├── hector_marker_drawing
│   ├── hector_nav_msgs
│   ├── hector_slam
│   ├── hector_slam_launch
│   └── hector_trajectory_server
├── particle_filter
│   ├── CMakeLists.txt
│   ├── README.md
│   ├── docs
│   ├── launch
│   ├── maps
│   ├── media
│   ├── package.xml
│   ├── rviz
│   └── src
├── range_libc
│   ├── CMakeLists.txt
│   ├── README.md
│   ├── docs
│   ├── generate_serialized.sh
│   ├── includes
│   ├── license.txt
│   ├── main.cpp
│   ├── make_plots.py
│   ├── maps
│   ├── media
│   ├── pywrapper
│   ├── vendor
│   └── visualize.py
└── simulator
    ├── CMakeLists.txt
    ├── LICENSE
    ├── README.md
    ├── config
    ├── launch
    ├── map
    ├── package.xml
    ├── rviz
    ├── scripts
    ├── src
    ├── urdf
    └── world
```

It seems the package name is `simulator`, and the the contents of `launch` are: 

1. `racecar.access`
2. `simulator.master`

However attempting to use `racecar.access` fails too.

**Comment by varundevsukhil** [comment]
The package name is `f1tenth-sim` not `simulator` (this is just the folder name). The contents of the `launch` directory are accurate. Try the following in sequence:  

1. `roslaunch f1tenth-sim simulator.master`  
2. `roslaunch f1tenth-sim racecar.access`

If it does not work, post the terminal output here (entire terminal from launch command to the last printed line)

**Comment by Micrified** [comment]
@varundevsukhil The first command works correctly. Thank you so much for resolving my issue! 

In summary: The launch file has a typo in Wikipedia. I used the correct name in testing, but changed the package name to simulator in error (believing this was the correct package name). Now both are correct!

Much appreciated! :)
