### ISSUE TITLE
Intermediate Tutorials: PurePursuit repository is missing CMakeLists file 

### ISSUE THREAD

**Issue by Micrified** [f1tenth-dev/simulator#15]
The [intermediate tutorial](https://github.com/f1tenth-dev/simulator/wiki/Intermediate-Tutorials) provided in the handy Wiki mentions launching an autonomous driving node using the modified pure-pursuit algorithm. 

However, the installation does not include this repository. It can still be found as a package [here](https://github.com/f1tenth-dev/pure_pursuit) though. But downloading this package is not sufficient for `catkin` to build it, as it does not include the package CMakeLists file for building it. (Edit: Removed package.xml as it was not the needed file)

**Comment by varundevsukhil** [comment]
Unfortunately, the `pure_pursuit` algorithm is no longer part of the main simulator package. There is one of two ways in which you can get this algorithm working in the simulator:  

1. Move the scripts and launch files from the [pure_pursuit](https://github.com/f1tenth-dev/pure_pursuit) repository to the `simulator` directory individually such that each file is under the designated folder
2. Clone the `pure_pursuit` package to `src` directory in your local workspace, and within the `src` directory, execute `catkin_creake_pkg pure_pursuit`

Also note that we have removed trajectory data from the `pure_pursuit` package to support custom race track designs, so you will have to provide your own raceline data with a min. resolution of `0.05 meters`  

If you have further questions about the `pure_pursuit` package, please open a ticket in that repository so only `simulator` related issues are posted here.

**Comment by varundevsukhil** [comment]
Closed (no response for 20 days)
