### ISSUE TITLE
No navigation.yaml file in config

### ISSUE THREAD

**Issue by m-milena** [f1tenth-dev/simulator#16]
Hi, I am making your tutorial for begginer and I can't run navigation.launch file. Error:

RLException: unused args [car_name, paint, x_pos, run_gazebo, y_pos] for include of [/home/milena/ros_workspaces/autosim_ws/src/simulator/launch/simulator.master]
The traceback for the exception was written to the log file

When I comment it, I saw that there is no navigation.yaml file in config directory.

**Comment by varundevsukhil** [comment]
The tutorials have been moved to a [separate repository](https://github.com/f1tenth-dev/tutorials).
