### ISSUE TITLE
No 'simulator.launch' file

### ISSUE THREAD

**Issue by BDEvan5** [f1tenth-dev/simulator#17]
This is similar to issue #14, but I couldn't find a solution in that issue card that would work for me.

After following the installation instructions there are only two files in the launch folder, 'racecar.access' and 'simulator.master'.

Accordingly, I can run the first step in the tutorials (called 'first-time operation') but I can't run the 2nd step (called 'Keyboard Tele-Operation'). 
How do I find or generate a 'simulator.launch' file?

**Comment by Praj390** [comment]
You can use the simulator.master to launch the simulator and racecar.access to access the teleop operation. racecar.access have a keyboard teleop node and other nodes.

**Comment by BDEvan5** [comment]
Thank you so much for the help and the simulator. It is very useful.
