### ISSUE TITLE
/scan topic not being published

### ISSUE THREAD

**Issue by chris-wei-17** [f1tenth-dev/simulator#9]
Have there been any recent changes that would lead to the /scan topic not being published?  After launching everything it looks like most all other topics are there except for /scan almost as if Gazebo is missing the laser sensor in the xacro.

**Comment by varundevsukhil** [comment]
The simulator does not produce a standalone laserscan topic under `/scan`, but under the virtual racecar namespace `/car_name/scan`. Have you checked the topic under the racecar namespace? If not, can you post the output for the following command here?

```shell
$ rostopic list
```

The racecar xacro is modular, so it is possible that some arguments are missing from where the spawn service is being called. Are you using the launch file template provided with the simulator? If not, how are you creating the virtual racecar in Gazebo?

**Comment by varundevsukhil** [comment]
Stale topic
